#!/bin/bash

# Prepare the environment

# Download and exact Kafka
wget https://archive.apache.org/dist/kafka/2.8.0/kafka_2.12-2.8.0.tgz
tar -xzf kafka_2.12-2.8.0.tgz

#Prepare MySQL server
start_mysql

#Get the password and connect to the server
mysql --host=127.0.0.1 --port=3306 --user=root --password=Mjk0NDQtcnNhbm5h

#Create a databse named tolldata
create database tolldata;

#Create a table named livetolldata to store the data generated by the traffic simluatior 
use tolldata;

create table livetolldata(timestamp datetime,vehicle_id int,vehicle_type char(15),toll_plaza_id smallint);

#Disconnect The Server
exit

#Install kafka-python to cummunicate with kafka server
python3 -m pip install kafka-python

#Install the python module mysql-connector-python to interact with mysql server
python3 -m pip install mysql-connector-python==8.0.31



#Start Kafka

#Start Zookeeper
cd kafka_2.12-2.8.0
bin/zookeeper-server-start.sh config/zookeeper.properties

#Open a new terminal to start Kafka Server
cd kafka_2.12-2.8.0
bin/kafka-server-start.sh config/server.properties 